version: '3'

services:
  web:
    build: .
    container_name: promptvault-app
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - promptvault-network

networks:
  promptvault-network:
    driver: bridge
